import canonicalLaneMathlib.AdmissibleClass
import ConvergenceFactorsSummabilityFactorsLemmaCanonicalLaneLean.ConvergenceFactorsBridge
import ConvergenceFactorsSummabilityFactorsLemmaCanonicalLaneLean.SummabilityFactorsGate

namespace HautevilleHouse
namespace ConvergenceFactorsSummabilityFactorsLemmaCanonicalLaneLean

def ConstrainedConvergenceFactorsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_convergence_factors_endgame (A : AdmissibleClass) : ConstrainedConvergenceFactorsClosure A :=
  And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ConvergenceFactorsSummabilityFactorsLemmaCanonicalLaneLean
end HautevilleHouse